<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hammed Akande">

<title>EDUC 6003 Advanced Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">EDUC 6003 Advanced Statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#chapter-1" id="toc-chapter-1" class="nav-link active" data-scroll-target="#chapter-1">Chapter 1</a>
  <ul class="collapse">
  <li><a href="#introduction-to-reliability-index-analysis" id="toc-introduction-to-reliability-index-analysis" class="nav-link" data-scroll-target="#introduction-to-reliability-index-analysis">Introduction to Reliability Index Analysis</a>
  <ul class="collapse">
  <li><a href="#what-is-reliability" id="toc-what-is-reliability" class="nav-link" data-scroll-target="#what-is-reliability">What is Reliability?</a></li>
  </ul></li>
  <li><a href="#classical-test-theory-ctt-and-coefficient-alpha" id="toc-classical-test-theory-ctt-and-coefficient-alpha" class="nav-link" data-scroll-target="#classical-test-theory-ctt-and-coefficient-alpha">Classical Test Theory (CTT) and Coefficient Alpha</a>
  <ul class="collapse">
  <li><a href="#coefficient-alpha-cronbachs-alpha" id="toc-coefficient-alpha-cronbachs-alpha" class="nav-link" data-scroll-target="#coefficient-alpha-cronbachs-alpha">Coefficient Alpha (Cronbach’s Alpha)</a></li>
  <li><a href="#coefficient-omega" id="toc-coefficient-omega" class="nav-link" data-scroll-target="#coefficient-omega">Coefficient Omega</a></li>
  </ul></li>
  <li><a href="#calculations-in-r" id="toc-calculations-in-r" class="nav-link" data-scroll-target="#calculations-in-r">Calculations in R</a></li>
  <li><a href="#loading-the-bfi-dataset" id="toc-loading-the-bfi-dataset" class="nav-link" data-scroll-target="#loading-the-bfi-dataset">Loading the (BFI) dataset</a>
  <ul class="collapse">
  <li><a href="#selecting-openness-items" id="toc-selecting-openness-items" class="nav-link" data-scroll-target="#selecting-openness-items">Selecting Openness Items</a></li>
  <li><a href="#handling-missing-data" id="toc-handling-missing-data" class="nav-link" data-scroll-target="#handling-missing-data">Handling Missing Data</a></li>
  </ul></li>
  <li><a href="#calculating-cronbachs-alpha" id="toc-calculating-cronbachs-alpha" class="nav-link" data-scroll-target="#calculating-cronbachs-alpha">Calculating Cronbach’s Alpha</a>
  <ul class="collapse">
  <li><a href="#a.-we-can-use-the-psych-package-in-r" id="toc-a.-we-can-use-the-psych-package-in-r" class="nav-link" data-scroll-target="#a.-we-can-use-the-psych-package-in-r">a. We can use the psych Package in R</a></li>
  </ul></li>
  <li><a href="#confirmatory-factor-analysis-cfa" id="toc-confirmatory-factor-analysis-cfa" class="nav-link" data-scroll-target="#confirmatory-factor-analysis-cfa">Confirmatory Factor Analysis (CFA)</a>
  <ul class="collapse">
  <li><a href="#a.-specifying-the-cfa-model" id="toc-a.-specifying-the-cfa-model" class="nav-link" data-scroll-target="#a.-specifying-the-cfa-model">a. Specifying the CFA Model</a></li>
  <li><a href="#b.-fitting-the-cfa-model" id="toc-b.-fitting-the-cfa-model" class="nav-link" data-scroll-target="#b.-fitting-the-cfa-model">b. Fitting the CFA Model</a></li>
  </ul></li>
  <li><a href="#calculating-categorical-omega" id="toc-calculating-categorical-omega" class="nav-link" data-scroll-target="#calculating-categorical-omega">Calculating Categorical Omega</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">EDUC 6003 Advanced Statistics</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hammed Akande </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="chapter-1" class="level1">
<h1>Chapter 1</h1>
<section id="introduction-to-reliability-index-analysis" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-reliability-index-analysis">Introduction to Reliability Index Analysis</h2>
<p>This tutorial will serve as a Guide to Enhanced Reliability Estimation with R</p>
<section id="what-is-reliability" class="level3">
<h3 class="anchored" data-anchor-id="what-is-reliability">What is Reliability?</h3>
<p>Reliability refers to the consistency and precision of measurement instruments. In psychological testing, it assesses the extent to which a test produces stable and consistent results.</p>
<section id="importance-of-reliability" class="level4">
<h4 class="anchored" data-anchor-id="importance-of-reliability">Importance of Reliability</h4>
<p><em>Measurement Precision</em>: Ensures that the scores accurately reflect the true attributes being measured.</p>
<p><em>Research Validity</em>: High reliability is a prerequisite for valid conclusions and replicable research findings.</p>
<p><em>Error Reduction</em>: Minimizes the impact of random errors, enhancing the clarity of observed relationships between constructs.</p>
</section>
<section id="types-of-reliability" class="level4">
<h4 class="anchored" data-anchor-id="types-of-reliability">Types of Reliability</h4>
<p><em>Internal Consistency</em>: Degree to which items within a test measure the same construct.</p>
<p><em>Test-Retest Reliability</em>: Consistency of scores over time.</p>
<p><em>Inter-Rater Reliability</em>: Agreement between different raters or observers.</p>
</section>
</section>
</section>
<section id="classical-test-theory-ctt-and-coefficient-alpha" class="level2">
<h2 class="anchored" data-anchor-id="classical-test-theory-ctt-and-coefficient-alpha">Classical Test Theory (CTT) and Coefficient Alpha</h2>
<p>Classical Test Theory Overview: CTT posits that each observed score is composed of a true score and an error score:</p>
<p><span class="math display">\[ X = T + E \]</span></p>
<p>where:</p>
<p>𝑋= Observed score 𝑇= True score 𝐸= Error score</p>
<section id="coefficient-alpha-cronbachs-alpha" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-alpha-cronbachs-alpha">Coefficient Alpha (Cronbach’s Alpha)</h3>
<p>This is a widely used measure of internal consistency reliability within CTT. It estimates the extent to which items on a test measure the same underlying construct.</p>
<p><span class="math display">\[
\alpha = \frac{N}{N-1} \left(1 - \frac{\sum \sigma^2_{E}}{\sigma^2_{X}}\right)
\]</span></p>
<p>Where:</p>
<p><span class="math inline">\(\alpha\)</span> = Cronbach’s Alpha</p>
<p>𝑁 = Number of items in the test</p>
<p><span class="math inline">\(\sigma^2_{E}\)</span> = Variance of the error scores</p>
<p><span class="math inline">\(\sigma^2_{X}\)</span> = Variance of the observed total scores</p>
<section id="assumptions-of-alpha" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-of-alpha">Assumptions of Alpha</h4>
<p><em>Unidimensionality</em>: All items measure a single construct.</p>
<p><em>Tau Equivalence</em>: Each item has the same true score variance.</p>
<p><em>Independence of Errors</em>: Error terms are uncorrelated across items.</p>
</section>
<section id="limitations-of-alpha" class="level4">
<h4 class="anchored" data-anchor-id="limitations-of-alpha">Limitations of Alpha</h4>
<p><em>Sensitivity to Tau Equivalence</em>: Violations can lead to underestimation or overestimation of reliability.</p>
<p><em>Assumes Unidimensionality</em>: Not suitable for multidimensional scales without adjustments.</p>
<p><em>Ignores Factor Structure</em>: Does not account for the underlying factor model of the test.</p>
</section>
</section>
<section id="coefficient-omega" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-omega">Coefficient Omega</h3>
<p>Coefficient Omega is a more robust alternative to Cronbach’s Alpha, especially when the assumption of tau-equivalence (equal factor loadings) is violated. Omega takes into account the factor structure of the test, making it suitable for both unidimensional and multidimensional scales.</p>
<section id="types-of-omega" class="level4">
<h4 class="anchored" data-anchor-id="types-of-omega">Types of Omega</h4>
<p><em>Omega Total (ωₜ</em>): Accounts for all common factors, both general and specific.</p>
<p><em>Omega Hierarchical (ωₕ)</em>: Represents the proportion of variance attributable to a general factor alone.</p>
<p>Omega Total is given by:</p>
<p><span class="math display">\[
\omega_t = \frac{\sum_{i=1}^{k} \lambda_i}{\sum_{i=1}^{k} \lambda_i + \sum_{i=1}^{k} \theta_i}
\]</span></p>
<p>Where:</p>
<p><span class="math inline">\(\omega_t\)</span> = Omega Total</p>
<p><span class="math inline">\(\lambda_i\)</span> = Factor loading for item</p>
<p><span class="math inline">\(\theta_i\)</span> = Unique variance (error variance) for item</p>
<p><span class="math inline">\(k\)</span> = Total number of items</p>
<p>For a hierarchical model, Omega Hierarchical is:</p>
<p><span class="math display">\[
\omega_h = \frac{\lambda_g^2}{\lambda_g^2 + \sum_{i=1}^{k} \theta_i}
\]</span></p>
<p>where:</p>
<p><span class="math inline">\(\omega_h\)</span> = Omega Hierarchical</p>
<p><span class="math inline">\(\lambda_g\)</span> = Factor loading of the general factor</p>
<p><span class="math inline">\(\theta_i\)</span> = Unique variance for item <span class="math inline">\(i\)</span></p>
</section>
<section id="advantages-of-omega-over-alpha" class="level4">
<h4 class="anchored" data-anchor-id="advantages-of-omega-over-alpha">Advantages of Omega Over Alpha</h4>
<p><em>Factor Structure Incorporation</em>: Utilizes confirmatory factor analysis (CFA) to model the underlying structure.</p>
<p><em>Less Sensitive to Tau Equivalence Violations</em>: Provides more accurate reliability estimates when tau equivalence is not met.</p>
<p><em>Applicability to Multidimensional Scales</em>: Suitable for tests measuring multiple constructs.</p>
</section>
</section>
</section>
<section id="calculations-in-r" class="level2">
<h2 class="anchored" data-anchor-id="calculations-in-r">Calculations in R</h2>
<p>Here, I will walk through the step-by-step process of calculating Cronbach’s Alpha and Coefficient Omega using R.</p>
<p>Load the necessary packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(psych,lavaan,semTools,tidyverse,semTools,psych,tidyverse,lavaan,rio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-the-bfi-dataset" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-bfi-dataset">Loading the (BFI) dataset</h2>
<p>The Big Five Inventory (BFI) is a widely used dataset in personality psychology, measuring the five major dimensions of personality. We’ll focus on the Openness trait for this tutorial.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure you've loaded the psych package</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the BFI dataset</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(bfi)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># load data file</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>bfi <span class="ot">&lt;-</span> bfi</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bfi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "A1"        "A2"        "A3"        "A4"        "A5"        "C1"       
 [7] "C2"        "C3"        "C4"        "C5"        "E1"        "E2"       
[13] "E3"        "E4"        "E5"        "N1"        "N2"        "N3"       
[19] "N4"        "N5"        "O1"        "O2"        "O3"        "O4"       
[25] "O5"        "gender"    "education" "age"      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the structure of the dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#str(bfi)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The dataset contains 2,800 participants with various demographic and personality-related variables. A1 to A5 correspond to items measuring the Openness trait.</p>
<section id="selecting-openness-items" class="level3">
<h3 class="anchored" data-anchor-id="selecting-openness-items">Selecting Openness Items</h3>
<p>For this tutorial, we’ll focus on five items measuring the Openness trait. These items are typically labeled as A1 to A5 in the BFI dataset.</p>
<section id="a.-extracting-openness-items" class="level4">
<h4 class="anchored" data-anchor-id="a.-extracting-openness-items">a. Extracting Openness Items</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select columns that contain "O" in their names and remove rows with NA values</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>oppeness <span class="ot">&lt;-</span> bfi <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"^O"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(oppeness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  O1 O2 O3 O4 O5
1  3  6  3  4  3
2  4  2  4  3  3
3  4  2  5  5  2
4  3  3  4  3  5
5  3  3  4  3  3
6  4  3  5  6  1</code></pre>
</div>
</div>
<p>Each A variable represents a Likert-type item measuring Openness. Responses range from 1 to 6, treated as continuous variables for analysis.</p>
</section>
</section>
<section id="handling-missing-data" class="level3">
<h3 class="anchored" data-anchor-id="handling-missing-data">Handling Missing Data</h3>
<p>Before we continue, let’s check any missing data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(oppeness))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>In this dataset, there are no missing values in the Openness items. If missing values were present, then we need to address that.</p>
</section>
</section>
<section id="calculating-cronbachs-alpha" class="level2">
<h2 class="anchored" data-anchor-id="calculating-cronbachs-alpha">Calculating Cronbach’s Alpha</h2>
<p>Recall that Cronbach’s Alpha (α) is a measure of internal consistency that measures how closely related a set of items are as a group.</p>
<section id="a.-we-can-use-the-psych-package-in-r" class="level3">
<h3 class="anchored" data-anchor-id="a.-we-can-use-the-psych-package-in-r">a. We can use the psych Package in R</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Cronbach's Alpha using the psych package</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#alpha_result &lt;- psych::alpha(oppeness)</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#print(alpha_result)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Because some items were negatively correlated with the first principal component, we probably should reverse them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reversing item O2 and O5</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"O2"</span>,<span class="st">"O5"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>reverse <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  x.reversed <span class="ot">&lt;-</span> <span class="dv">7</span> <span class="sc">+</span><span class="dv">0</span> <span class="sc">-</span> x</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>oppeness[, <span class="fu">c</span>(<span class="st">"O2R"</span>, <span class="st">"O5R"</span>)] <span class="ot">&lt;-</span> <span class="fu">reverse</span>(oppeness[,<span class="fu">c</span>(<span class="st">"O2"</span>,<span class="st">"O5"</span>)])</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># compare original and reversed responses</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>oppeness[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  O1 O2 O3 O4 O5 O2R O5R
1  3  6  3  4  3   1   4
2  4  2  4  3  3   5   4
3  4  2  5  5  2   5   5
4  3  3  4  3  5   4   2
5  3  3  4  3  3   4   4
6  4  3  5  6  1   4   6</code></pre>
</div>
</div>
<p>Now, we can compute the alpha</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute alpha coefficient </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>alpha_result <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(oppeness[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>)])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(alpha_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = oppeness[, -c(2, 5)])

  raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
       0.6      0.61    0.57      0.24 1.6 0.012  4.6 0.81     0.23

    95% confidence boundaries 
         lower alpha upper
Feldt     0.58   0.6  0.63
Duhachek  0.58   0.6  0.63

 Reliability if an item is dropped:
    raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
O1       0.54      0.54    0.48      0.23 1.2    0.014 0.0087  0.23
O3       0.50      0.50    0.44      0.20 1.0    0.015 0.0065  0.20
O4       0.61      0.62    0.56      0.29 1.7    0.012 0.0040  0.29
O2R      0.57      0.57    0.51      0.25 1.3    0.014 0.0077  0.21
O5R      0.52      0.53    0.48      0.22 1.1    0.015 0.0109  0.21

 Item statistics 
       n raw.r std.r r.cor r.drop mean  sd
O1  2726  0.61  0.65  0.51   0.39  4.8 1.1
O3  2726  0.68  0.69  0.59   0.45  4.4 1.2
O4  2726  0.50  0.52  0.29   0.22  4.9 1.2
O2R 2726  0.66  0.60  0.44   0.34  4.3 1.6
O5R 2726  0.67  0.66  0.52   0.42  4.5 1.3

Non missing response frequency for each item
       1    2    3    4    5    6 miss
O1  0.01 0.04 0.08 0.22 0.33 0.33    0
O3  0.03 0.05 0.10 0.28 0.34 0.20    0
O4  0.02 0.05 0.06 0.17 0.32 0.39    0
O2R 0.06 0.10 0.15 0.14 0.26 0.29    0
O5R 0.02 0.07 0.13 0.19 0.32 0.27    0</code></pre>
</div>
</div>
<p>Explanation:</p>
<p>raw_alpha: The Cronbach’s Alpha coefficient.</p>
<p>std.alpha: Standardized alpha, similar to raw_alpha.</p>
<p>G6(smc): Generalizability theory estimate with squared multiple correlations.</p>
<p>average_r: Average inter-item correlation.</p>
<p>S/N: Signal-to-noise ratio.</p>
<p>ase: Asymptotic standard error.</p>
<p>Confidence Intervals: Lower and upper bounds for alpha.</p>
<p>As we can see, the Cronbach’s Alpha for the Openness items is 0.6, indicating strong internal consistency. The average inter-item correlation is 0.24, moderate and within psychological scales.</p>
</section>
</section>
<section id="confirmatory-factor-analysis-cfa" class="level2">
<h2 class="anchored" data-anchor-id="confirmatory-factor-analysis-cfa">Confirmatory Factor Analysis (CFA)</h2>
<p>Confirmatory Factor Analysis (CFA) is used to verify the factor structure of a set of observed variables. In our case, we assume a unidimensional structure.</p>
<section id="a.-specifying-the-cfa-model" class="level3">
<h3 class="anchored" data-anchor-id="a.-specifying-the-cfa-model">a. Specifying the CFA Model</h3>
<p>Let’s specify a one-factor model where all items load on a single latent factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify model</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mod1f <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="st">openness =~ O1 + O2R + O3 + O4 + O5R</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="b.-fitting-the-cfa-model" class="level3">
<h3 class="anchored" data-anchor-id="b.-fitting-the-cfa-model">b. Fitting the CFA Model</h3>
<p>Fit the Model Using lavaan:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#pacman::p_load(lavaan)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate model</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>fit.one.f <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod1f, <span class="at">data=</span>oppeness, <span class="at">std.lv=</span>T, <span class="at">missing=</span><span class="st">'direct'</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">estimator=</span><span class="st">'MLR'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># The results can be viewed using the summary</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.one.f, <span class="at">fit.measures=</span>T, <span class="at">standardized=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 22 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        15

  Number of observations                          2726
  Number of missing patterns                         1

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                                80.583      67.248
  Degrees of freedom                                 5           5
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  1.198
    Yuan-Bentler correction (Mplus variant)                       

Model Test Baseline Model:

  Test statistic                              1375.389    1049.226
  Degrees of freedom                                10          10
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.311

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.945       0.940
  Tucker-Lewis Index (TLI)                       0.889       0.880
                                                                  
  Robust Comparative Fit Index (CFI)                         0.946
  Robust Tucker-Lewis Index (TLI)                            0.891

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -22078.661  -22078.661
  Scaling correction factor                                  1.167
      for the MLR correction                                      
  Loglikelihood unrestricted model (H1)     -22038.369  -22038.369
  Scaling correction factor                                  1.174
      for the MLR correction                                      
                                                                  
  Akaike (AIC)                               44187.322   44187.322
  Bayesian (BIC)                             44275.980   44275.980
  Sample-size adjusted Bayesian (SABIC)      44228.321   44228.321

Root Mean Square Error of Approximation:

  RMSEA                                          0.074       0.068
  90 Percent confidence interval - lower         0.061       0.055
  90 Percent confidence interval - upper         0.089       0.081
  P-value H_0: RMSEA &lt;= 0.050                    0.002       0.012
  P-value H_0: RMSEA &gt;= 0.080                    0.280       0.066
                                                                  
  Robust RMSEA                                               0.074
  90 Percent confidence interval - lower                     0.058
  90 Percent confidence interval - upper                     0.090
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.006
  P-value H_0: Robust RMSEA &gt;= 0.080                         0.285

Standardized Root Mean Square Residual:

  SRMR                                           0.029       0.029

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  openness =~                                                           
    O1                0.616    0.029   21.346    0.000    0.616    0.546
    O2R               0.701    0.041   17.170    0.000    0.701    0.449
    O3                0.792    0.032   24.649    0.000    0.792    0.649
    O4                0.357    0.030   11.749    0.000    0.357    0.294
    O5R               0.685    0.036   19.194    0.000    0.685    0.517

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .O1                4.819    0.022  223.110    0.000    4.819    4.273
   .O2R               4.300    0.030  143.782    0.000    4.300    2.754
   .O3                4.439    0.023  189.916    0.000    4.439    3.637
   .O4                4.898    0.023  210.231    0.000    4.898    4.027
   .O5R               4.516    0.025  177.976    0.000    4.516    3.409

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .O1                0.893    0.037   23.923    0.000    0.893    0.702
   .O2R               1.947    0.068   28.607    0.000    1.947    0.798
   .O3                0.862    0.050   17.172    0.000    0.862    0.579
   .O4                1.352    0.052   25.967    0.000    1.352    0.914
   .O5R               1.286    0.059   21.822    0.000    1.286    0.732
    openness          1.000                               1.000    1.000</code></pre>
</div>
</div>
<p>Explanation:</p>
<p>Estimator: Maximum Likelihood (ML).</p>
<p>Test Statistics: The Chi-square test is significant (𝑝&lt;0.001), indicating a poor fit.</p>
<p>Fit Indices:</p>
<p>CFI (0.94): above 0.90.</p>
<p>TLI (0.88): Below the threshold of 0.90.</p>
<p>RMSEA (0.068): Indicates relatively weak fit (≥0.05).</p>
<p>SRMR (0.029): Great fit (≤0.08).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(fit.one.f, <span class="at">type=</span><span class="st">'cor'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$type
[1] "cor.bollen"

$cov
        O1    O2R     O3     O4    O5R
O1   0.000                            
O2R -0.026  0.000                     
O3   0.037 -0.024  0.000              
O4   0.013 -0.052  0.000  0.000       
O5R -0.044  0.090 -0.022  0.027  0.000

$mean
 O1 O2R  O3  O4 O5R 
  0   0   0   0   0 </code></pre>
</div>
</div>
<p>The fit statistics from the Robust column in the summary suggest that this one-factor model provides a moderate fit to the data. While the Comparative Fit Index (CFI) of 0.94 indicates an acceptable fit, the Tucker-Lewis Index (TLI) of 0.88 is relatively lower, and the Root Mean Square Error of Approximation (RMSEA) is relatively high at 0.08.</p>
<p>The factor loadings (𝜆̂) show significant variation, ranging from 0.357 to 0.792, which implies that the assumption of equal loadings (tau equivalence) does not hold for this openness test. As a result, omega (ωu) should be a more suitable measure of reliability than Cronbach’s alpha. We can compute the ωu estimate by running the <code>reliability</code> function from the semTools package on the one-factor model object (<code>fit1f</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">reliability</span>(fit.one.f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        openness
alpha  0.6025464
omega  0.6103741
omega2 0.6103741
omega3 0.6098642
avevar 0.2484010</code></pre>
</div>
</div>
<p><code>omega</code> and <code>omega2</code> measure reliability based on the variance expected by the model, while <code>omega3</code> measures it based on the actual variance seen in your data. The small difference between <code>omega</code> and <code>omega3</code> suggests that the model’s predictions of variance are somewhat close to what’s observed in the sample.</p>
</section>
</section>
<section id="calculating-categorical-omega" class="level2">
<h2 class="anchored" data-anchor-id="calculating-categorical-omega">Calculating Categorical Omega</h2>
<p>Recall that Coefficient Omega (ω) is a reliability estimate that accounts for the factor structure of the test, providing a more accurate measure than Cronbach’s Alpha, especially in the presence of multidimensionality or when tau-equivalence is violated.</p>
<p>Since factor loadings derived from polychoric correlations represent the link between the factor and the underlying latent response variables (not the actual responses from the items), using the ωu formula here would tell us how much of the variance in the latent response variables is explained by the factor. However, this doesn’t reflect the true variance in the sum of the observed item responses. Essentially, in this case, ωu would give us the reliability of a hypothetical total score based on the latent variables rather than the actual observed total score.</p>
<p>To correct for this, Green and Yang (2009b) proposed a new reliability estimate called ωu-cat, which adjusts the reliability calculation to align with the observed total score. This estimate is more accurate for unidimensional scales with categorical items, especially when the response patterns vary across items.</p>
<p>Since the psychoticism items use a 4-point rating scale, I fit the one-factor model using polychoric correlations and the WLSMV estimator (weighted least squares with mean and variance adjustment). This approach is recommended for confirmatory factor analysis involving polychoric correlations, as it is more robust than the maximum likelihood (ML) estimator.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load the data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>potic <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">"potic.csv"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify model</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>mod.one.fCat <span class="ot">&lt;-</span> <span class="st">'psyctcsm =~ DDP1 + DDP2 +</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="st">DDP3 + DDP4'</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate model</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>fit.one.fCat <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod.one.fCat, <span class="at">data=</span>potic, <span class="at">std.lv=</span><span class="cn">TRUE</span>, <span class="at">ordered=</span>T, <span class="at">estimator=</span><span class="st">'WLSMV'</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieving the results</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.one.fCat, <span class="at">fit.measures=</span><span class="cn">TRUE</span>, <span class="at">standardized=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 10 iterations

  Estimator                                       DWLS
  Optimization method                           NLMINB
  Number of model parameters                        20

                                                  Used       Total
  Number of observations                           498         500

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                                 7.117      14.910
  Degrees of freedom                                 2           2
  P-value (Chi-square)                           0.028       0.001
  Scaling correction factor                                  0.480
  Shift parameter                                            0.089
    simple second-order correction                                

Model Test Baseline Model:

  Test statistic                              1635.647    1316.086
  Degrees of freedom                                 6           6
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.244

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.997       0.990
  Tucker-Lewis Index (TLI)                       0.991       0.970
                                                                  
  Robust Comparative Fit Index (CFI)                         0.969
  Robust Tucker-Lewis Index (TLI)                            0.908

Root Mean Square Error of Approximation:

  RMSEA                                          0.072       0.114
  90 Percent confidence interval - lower         0.020       0.065
  90 Percent confidence interval - upper         0.132       0.171
  P-value H_0: RMSEA &lt;= 0.050                    0.200       0.019
  P-value H_0: RMSEA &gt;= 0.080                    0.479       0.880
                                                                  
  Robust RMSEA                                               0.147
  90 Percent confidence interval - lower                     0.089
  90 Percent confidence interval - upper                     0.213
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.004
  P-value H_0: Robust RMSEA &gt;= 0.080                         0.970

Standardized Root Mean Square Residual:

  SRMR                                           0.033       0.033

Parameter Estimates:

  Parameterization                               Delta
  Standard errors                           Robust.sem
  Information                                 Expected
  Information saturated (h1) model        Unstructured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  psyctcsm =~                                                           
    DDP1              0.894    0.028   31.538    0.000    0.894    0.894
    DDP2              0.753    0.028   26.711    0.000    0.753    0.753
    DDP3              0.698    0.030   23.314    0.000    0.698    0.698
    DDP4              0.513    0.040   12.738    0.000    0.513    0.513

Thresholds:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    DDP1|t1          -0.716    0.062  -11.591    0.000   -0.716   -0.716
    DDP1|t2          -0.040    0.056   -0.716    0.474   -0.040   -0.040
    DDP1|t3           0.296    0.057    5.185    0.000    0.296    0.296
    DDP1|t4           1.034    0.069   15.065    0.000    1.034    1.034
    DDP2|t1          -0.580    0.060   -9.693    0.000   -0.580   -0.580
    DDP2|t2           0.208    0.057    3.668    0.000    0.208    0.208
    DDP2|t3           0.562    0.060    9.431    0.000    0.562    0.562
    DDP2|t4           1.096    0.070   15.570    0.000    1.096    1.096
    DDP3|t1          -1.203    0.074  -16.298    0.000   -1.203   -1.203
    DDP3|t2          -0.425    0.058   -7.318    0.000   -0.425   -0.425
    DDP3|t3           0.081    0.056    1.432    0.152    0.081    0.081
    DDP3|t4           0.913    0.066   13.909    0.000    0.913    0.913
    DDP4|t1          -1.605    0.092  -17.382    0.000   -1.605   -1.605
    DDP4|t2          -1.060    0.069  -15.285    0.000   -1.060   -1.060
    DDP4|t3          -0.521    0.059   -8.817    0.000   -0.521   -0.521
    DDP4|t4           0.431    0.058    7.406    0.000    0.431    0.431

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .DDP1              0.201                               0.201    0.201
   .DDP2              0.433                               0.433    0.433
   .DDP3              0.513                               0.513    0.513
   .DDP4              0.737                               0.737    0.737
    psyctcsm          1.000                               1.000    1.000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate reliability</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">reliability</span>(fit.one.fCat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For constructs with categorical indicators, Zumbo et al.`s (2007) "ordinal alpha" is calculated in addition to the standard alpha, which treats ordinal variables as numeric. See Chalmers (2018) for a critique of "alpha.ord" and the response by Zumbo &amp; Kroc (2019). Likewise, average variance extracted is calculated from polychoric (polyserial) not Pearson correlations.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>           psyctcsm
alpha     0.7680870
alpha.ord 0.8007496
omega     0.7902953
omega2    0.7902953
omega3    0.7932682
avevar    0.5289638</code></pre>
</div>
</div>
<p>We can see that we have two estimates Cronbach’s alpha and differ a bit (0.80 &amp; 0.77). The is because the 2nd alpha estimate is an example of ordinal alpha, which is calculated using a model based on polychoric correlations, while the first alpha was derived using the standard method based on product-moment covariances between the items. It’s important to note that ordinal alpha measures the reliability of the sum of the continuous, latent-response variables rather than the observed categorical item responses. Additionally, it still assumes equal factor loadings (tau equivalence). Because of these limitations, I suggest disregarding the alpha value reported by semTools::reliability when the model uses polychoric correlations.</p>
<p>The values shown in the <code>omega</code> and <code>omega2</code> rows represent the ωu-cat estimate. The <code>omega3</code> row shows a variation where the denominator uses the observed sample variance of ( X ). So, we can see ωu-cat estimates suggest that 79% of the variance in the total score for the psychoticism scale is explained by the single psychoticism factor.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>